fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        website:
            client: default
            index_name: "open-awesome"
            types:
                system:
                    mappings:
                        id:
                        uuid: { boost: 5 }
                        hostname: { boost: 3 }
                        domain:
                        fqdn:
                        description:
                        type:
                        icon:
                        osGroup:
                        osFamily:
                        osName:
                        osVersion:
                        linkedSys:
                        serial:
                        model:
                        manufacturer:
                        uptime:
                        formFactor:
                        pcOsBit:
                        pcMemory:
                        pcNumProcessor:
                        pcDateOsInstallation:
                        printerPortName:
                        printerShared:
                        printerSharedName:
                        printerColor:
                        printerDuplex:
                        manOsGroup:
                        manOsFamily:
                        manOsName:
                        manDomain:
                        manStatus:
                        manEnvironment:
                        manCriticality:
                        manClass:
                        manDescription:
                        manFunction:
                        manType:
                        manIpAddress:
                        manOwner:
                        manOrgId:
                        manLocationId:
                        manLocationSuite:
                        manLocationRoom:
                        manLocationRack:
                        manLocationRackPosition:
                        manLocationRackSize:
                        manSerial:
                        manAssetNumber:
                        manModel:
                        manManufacturer:
                        manFormFactor:
                        manIcon:
                        manVmServerName:
                        manVmSystemId:
                        manVmGroup:
                        manClusterName:
                        invoiceId:
                        manPurchaseInvoice:
                        manPurchaseOrderNumber:
                        manPurchaseCostCenter:
                        manPurchaseVendor:
                        manPurchaseDate:
                        manPurchaseAmount:
                        manWarrantyDuration:
                        manWarrantyExpires:
                        manWarrantyType:
                        manTerminalNumber:
                        manSwitchId:
                        manSwitchPort:
                        manPatchPanel:
                        manPatchPanelPort:
                        manWallPort:
                        manPicture:
                        contactName:
                        contactId:
                        manServiceNumber:
                        manServiceProvider:
                        manServiceType:
                        manServicePlan:
                        manServiceNetwork:
                        manUnlockPin:
                        manSerialImei:
                        manSerialSim:
                        nmapType:
                        lastSeen:
                        lastSeenBy:
                        lastUser:
                        accessDetails:
                        snmpOid:
                        nmisGroup:
                        nmisName:
                        nmisRole:
                        systemKeyType:
                    persistence:
                        driver: orm
                        model: Ehann\Bundle\OpenAwesomeBundle\Entity\System
                        provider: ~
                bios:
                    mappings:
                        id:
                        description:
                        manufacturer:
                        serial:
                        smversion:
                        version:
                        assetTag:
                    persistence:
                        driver: orm
                        model: Ehann\Bundle\OpenAwesomeBundle\Entity\SysHwBios
                        provider: ~
                software:
                    mappings:
                        id:
                        name:
                        version:
                        description:
                        location:
                        version:
                        uninstall:
                        installDate:
                        installedBy:
                        installedOn:
                        publisher:
                        installSource:
                        systemComponent:
                        url:
                        email:
                        comment:
                        manComment:
                        count:
                        codeBase:
                        status:
                        key:
                        keyRelease:
                        keyEdition:
                    persistence:
                        driver: orm
                        model: Ehann\Bundle\OpenAwesomeBundle\Entity\SysSwSoftware
                        provider: ~
                scsi_controller:
                    mappings:
                        id:
                        name:
                        manufacturer:
                        deviceId:
                        type:
                    persistence:
                        driver: orm
                        model: Ehann\Bundle\OpenAwesomeBundle\Entity\SysHwScsiController
                        provider: ~
                processor:
                    mappings:
                        id:
                        cores:
                        description:
                        speed:
                        manufacturer:
                        powerManagementSupported:
                    persistence:
                        driver: orm
                        model: Ehann\Bundle\OpenAwesomeBundle\Entity\SysHwProcessor
                        provider: ~
                motherboard:
                    mappings:
                        id:
                        manufacturer:
                        model:
                        serial:
                        memorySlots:
                        processorSlots:
                        processorType:
                    persistence:
                        driver: orm
                        model: Ehann\Bundle\OpenAwesomeBundle\Entity\SysHwMotherboard
                        provider: ~
                optical_drive:
                    mappings:
                        id:
                        caption:
                        model:
                        deviceId:
                        mountPoint:
                    persistence:
                        driver: orm
                        model: Ehann\Bundle\OpenAwesomeBundle\Entity\SysHwOpticalDrive
                        provider: ~
                video_card:
                    mappings:
                        id:
                        description:
                        manufacturer:
                        currentHorizontalRes:
                        currentVerticalRes:
                        memory:
                        caption:
                        currentNumberColours:
                        currentRefreshRate:
                        deviceId:
                        driverDate:
                        driverVersion:
                        maxRefreshRate:
                        minRefreshRate:
                    persistence:
                        driver: orm
                        model: Ehann\Bundle\OpenAwesomeBundle\Entity\SysHwVideo
                        provider: ~
                monitor:
                    mappings:
                        id:
                        manufacturer:
                        deviceId:
                        manufactureDate:
                        model:
                        serial:
                        size:
                        aspectRatio:
                        manSerial:
                        edidVersion:
                        manDescription:
                        manValue:
                        manPurchaseOrderNumber:
                        manDatePurchased:
                    persistence:
                        driver: orm
                        model: Ehann\Bundle\OpenAwesomeBundle\Entity\SysHwMonitor
                        provider: ~
                sound_card:
                    mappings:
                        id:
                        manufacturer:
                        deviceId:
                        name:
                    persistence:
                        driver: orm
                        model: Ehann\Bundle\OpenAwesomeBundle\Entity\SysHwSound
                        provider: ~
                hard_drive:
                    mappings:
                        id:
                        caption:
                        index:
                        interfaceType:
                        manufacturer:
                        model:
                        serial:
                        partitions:
                        scsiBus:
                        scsiLogicalUnit:
                        scsiPort:
                        size:
                        deviceId:
                        status:
                    persistence:
                        driver: orm
                        model: Ehann\Bundle\OpenAwesomeBundle\Entity\SysHwHardDrive
                        provider: ~
