Ehann\Bundle\OpenAwesomeBundle\Entity\OaAssetLine:
    type: entity
    table: oa_asset_line
    id:
        lineId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: line_id
            generator:
                strategy: IDENTITY
    fields:
        orderId:
            type: integer
            nullable: true
            unsigned: true
            comment: ''
            column: order_id
        orgId:
            type: integer
            nullable: true
            unsigned: true
            comment: ''
            column: org_id
        selectId:
            type: integer
            nullable: true
            unsigned: true
            comment: ''
            column: select_id
        lineAmount:
            type: integer
            nullable: true
            unsigned: true
            comment: ''
            column: line_amount
        lineCostEach:
            type: integer
            nullable: true
            unsigned: true
            comment: ''
            column: line_cost_each
        lineTaxEach:
            type: integer
            nullable: true
            unsigned: true
            comment: ''
            column: line_tax_each
        lineAssetNumber:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: line_asset_number
        lineGl:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: line_gl
        lineType:
            type: string
            nullable: false
            length: null
            fixed: false
            comment: ''
            default: ''
            column: line_type
        lineSwLicenseExpiresDate:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
            column: line_sw_license_expires_date
        lineSwLicenseKey:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: line_sw_license_key
        lineSwLicenseNumber:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: line_sw_license_number
        lineSwLicenseAgreement:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: line_sw_license_agreement
        lineSwLicenseType:
            type: string
            nullable: false
            length: null
            fixed: false
            comment: ''
            default: ''
            column: line_sw_license_type
        lineVendorProducitId:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: line_vendor_producit_id
        lineVendorPartId:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: line_vendor_part_id
        lineMaintenanceIncluded:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: line_maintenance_included
        lineMaintenanceDateExpires:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
            column: line_maintenance_date_expires
        allocateType:
            type: string
            nullable: false
            length: null
            fixed: false
            comment: ''
            default: ''
            column: allocate_type
        allocateText:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            default: ''
            column: allocate_text
    lifecycleCallbacks: {  }
