Ehann\Bundle\OpenAwesomeBundle\Entity\OaAuditLog:
    type: entity
    table: oa_audit_log
    indexes:
        user_id:
            columns:
                - user_id
        oa_audit_log_system_id:
            columns:
                - system_id
    id:
        auditLogId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: audit_log_id
            generator:
                strategy: IDENTITY
    fields:
        auditLogEventType:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: audit_log_event_type
        auditLogEventDetails:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            column: audit_log_event_details
        timestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
    manyToOne:
        system:
            targetEntity: System
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                system_id:
                    referencedColumnName: system_id
            orphanRemoval: false
        user:
            targetEntity: OaUser
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: user_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
