Ehann\Bundle\OpenAwesomeBundle\Entity\OaChangeLog:
    type: entity
    table: oa_change_log
    indexes:
        change_id:
            columns:
                - change_id
        oa_change_log_user_id:
            columns:
                - user_id
    id:
        changeLogId:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: change_log_id
            generator:
                strategy: IDENTITY
    fields:
        changeLogAttachment:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            default: ''
            column: change_log_attachment
        changeLogComments:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: change_log_comments
        timestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
    manyToOne:
        change:
            targetEntity: OaChange
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                change_id:
                    referencedColumnName: change_id
            orphanRemoval: false
        user:
            targetEntity: OaUser
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: user_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
