Ehann\Bundle\OpenAwesomeBundle\Entity\OaConnection:
    type: entity
    table: oa_connection
    id:
        connectionId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: connection_id
            generator:
                strategy: IDENTITY
    fields:
        orgId:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: org_id
        name:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        provider:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        serviceType:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: service_type
        productName:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: product_name
        serviceIdentifier:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: service_identifier
        speed:
            type: float
            nullable: false
            precision: 7
            scale: 3
            comment: ''
            default: '0.000'
        locationIdA:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: location_id_a
        locationIdB:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: location_id_b
        systemIdA:
            type: integer
            nullable: true
            unsigned: true
            comment: ''
            column: system_id_a
        systemIdB:
            type: integer
            nullable: true
            unsigned: true
            comment: ''
            column: system_id_b
        lineNumberA:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: line_number_a
        lineNumberB:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: line_number_b
        ipAddressExternalA:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
            column: ip_address_external_a
        ipAddressExternalB:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
            column: ip_address_external_b
        ipAddressInternalA:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
            column: ip_address_internal_a
        ipAddressInternalB:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
            column: ip_address_internal_b
    lifecycleCallbacks: {  }
