Ehann\Bundle\OpenAwesomeBundle\Entity\OaGroupUser:
    type: entity
    table: oa_group_user
    indexes:
        user_id:
            columns:
                - user_id
        group_id:
            columns:
                - group_id
    id:
        groupUserId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: group_user_id
            generator:
                strategy: IDENTITY
    fields:
        groupUserAccessLevel:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: group_user_access_level
    manyToOne:
        group:
            targetEntity: OaGroup
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                group_id:
                    referencedColumnName: group_id
            orphanRemoval: false
        user:
            targetEntity: OaUser
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: user_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
