Ehann\Bundle\OpenAwesomeBundle\Entity\OaGroupSys:
    type: entity
    table: oa_group_sys
    indexes:
        system_id:
            columns:
                - system_id
        group_id:
            columns:
                - group_id
    id:
        groupSysId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: group_sys_id
            generator:
                strategy: IDENTITY
    fields:
        groupSysType:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            column: group_sys_type
    manyToOne:
        group:
            targetEntity: OaGroup
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                group_id:
                    referencedColumnName: group_id
            orphanRemoval: false
        system:
            targetEntity: System
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                system_id:
                    referencedColumnName: system_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
