Ehann\Bundle\OpenAwesomeBundle\Entity\OaGroupColumn:
    type: entity
    table: oa_group_column
    indexes:
        group_id:
            columns:
                - group_id
    id:
        columnId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: column_id
            generator:
                strategy: IDENTITY
    fields:
        columnOrder:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            column: column_order
        columnName:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: column_name
        columnVariable:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: column_variable
        columnType:
            type: string
            nullable: false
            length: null
            fixed: false
            comment: ''
            default: ''
            column: column_type
        columnLink:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: column_link
        columnSecondary:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: column_secondary
        columnTernary:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: column_ternary
        columnAlign:
            type: string
            nullable: false
            length: 6
            fixed: false
            comment: ''
            column: column_align
    manyToOne:
        group:
            targetEntity: OaGroup
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                group_id:
                    referencedColumnName: group_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
