Ehann\Bundle\OpenAwesomeBundle\Entity\OaOrg:
    type: entity
    table: oa_org
    id:
        orgId:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: org_id
            generator:
                strategy: IDENTITY
    fields:
        orgName:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: org_name
        orgParentId:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: org_parent_id
        orgGroupId:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: org_group_id
        contactId:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: contact_id
        orgPicture:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: org_picture
        orgComments:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: org_comments
    lifecycleCallbacks: {  }
