Ehann\Bundle\OpenAwesomeBundle\Entity\OaReport:
    type: entity
    table: oa_report
    id:
        reportId:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: report_id
            generator:
                strategy: IDENTITY
    fields:
        reportName:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: report_name
        reportDescription:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: report_description
        reportDisplayInMenu:
            type: string
            nullable: false
            length: null
            fixed: false
            comment: ''
            default: y
            column: report_display_in_menu
        reportSql:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: report_sql
        reportDisplaySql:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: report_display_sql
        reportViewFile:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: report_view_file
        reportViewContents:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: report_view_contents
        reportProcessing:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: report_processing
        reportSortColumn:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            column: report_sort_column
    lifecycleCallbacks: {  }
