Ehann\Bundle\OpenAwesomeBundle\Entity\OaUser:
    type: entity
    table: oa_user
    id:
        userId:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: user_id
            generator:
                strategy: IDENTITY
    fields:
        userName:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: user_name
        userPassword:
            type: string
            nullable: false
            length: 250
            fixed: false
            comment: ''
            column: user_password
        userFullName:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: user_full_name
        userEmail:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: user_email
        userLang:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: user_lang
        userDisplayNumber:
            type: smallint
            nullable: false
            unsigned: false
            comment: ''
            default: '10'
            column: user_display_number
        userTheme:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: user_theme
        userAdmin:
            type: string
            nullable: false
            length: 1
            fixed: false
            comment: ''
            column: user_admin
        userActive:
            type: string
            nullable: false
            length: 1
            fixed: false
            comment: ''
            default: y
            column: user_active
        userChange:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '1'
            column: user_change
        userSam:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '1'
            column: user_sam
    lifecycleCallbacks: {  }
