Ehann\Bundle\OpenAwesomeBundle\Entity\SysHwMotherboard:
    type: entity
    table: sys_hw_motherboard
    indexes:
        system_id:
            columns:
                - system_id
    id:
        motherboardId:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: motherboard_id
            generator:
                strategy: IDENTITY
    fields:
        manufacturer:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            default: ''
        model:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            default: ''
        serial:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
        memorySlots:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: memory_slots
        processorSlots:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: processor_slots
        processorType:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: processor_type
        timestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
        firstTimestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
            column: first_timestamp
    manyToOne:
        system:
            targetEntity: System
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                system_id:
                    referencedColumnName: system_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
