Ehann\Bundle\OpenAwesomeBundle\Entity\SysHwHardDrive:
    type: entity
    table: sys_hw_hard_drive
    indexes:
        hard_drive_index:
            columns:
                - hard_drive_index
        system_id:
            columns:
                - system_id
    id:
        hardDriveId:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: hard_drive_id
            generator:
                strategy: IDENTITY
    fields:
        hardDriveCaption:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: hard_drive_caption
        hardDriveIndex:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: hard_drive_index
        hardDriveInterfaceType:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
            default: ''
            column: hard_drive_interface_type
        hardDriveManufacturer:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: hard_drive_manufacturer
        hardDriveModel:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: hard_drive_model
        hardDriveSerial:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: hard_drive_serial
        hardDrivePartitions:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: hard_drive_partitions
        hardDriveScsiBus:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
            default: ''
            column: hard_drive_scsi_bus
        hardDriveScsiLogicalUnit:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: hard_drive_scsi_logical_unit
        hardDriveScsiPort:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
            default: ''
            column: hard_drive_scsi_port
        hardDriveSize:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: hard_drive_size
        hardDriveDeviceId:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            default: ''
            column: hard_drive_device_id
        hardDriveStatus:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: hard_drive_status
        timestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
        firstTimestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
            column: first_timestamp
    manyToOne:
        system:
            targetEntity: System
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                system_id:
                    referencedColumnName: system_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
