Ehann\Bundle\OpenAwesomeBundle\Entity\SysHwOpticalDrive:
    type: entity
    table: sys_hw_optical_drive
    indexes:
        system_id:
            columns:
                - system_id
    id:
        opticalDriveId:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: optical_drive_id
            generator:
                strategy: IDENTITY
    fields:
        opticalDriveCaption:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: optical_drive_caption
        opticalDriveModel:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: optical_drive_model
        opticalDriveDeviceId:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: optical_drive_device_id
        opticalDriveMountPoint:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
            default: ''
            column: optical_drive_mount_point
        timestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
        firstTimestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
            column: first_timestamp
    manyToOne:
        system:
            targetEntity: System
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                system_id:
                    referencedColumnName: system_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
