Ehann\Bundle\OpenAwesomeBundle\Entity\SysHwProcessor:
    type: entity
    table: sys_hw_processor
    indexes:
        system_id:
            columns:
                - system_id
    id:
        processorId:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: processor_id
            generator:
                strategy: IDENTITY
    fields:
        processorCores:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: processor_cores
        processorDescription:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: processor_description
        processorSpeed:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: processor_speed
        processorManufacturer:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: processor_manufacturer
        processorPowerManagementSupported:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            default: ''
            column: processor_power_management_supported
        timestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
        firstTimestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
            column: first_timestamp
    manyToOne:
        system:
            targetEntity: System
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                system_id:
                    referencedColumnName: system_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
