Ehann\Bundle\OpenAwesomeBundle\Entity\SysHwNetworkCardIp:
    type: entity
    table: sys_hw_network_card_ip
    indexes:
        id:
            columns:
                - net_mac_address
        sys_hw_network_card_ip_system_id:
            columns:
                - system_id
    id:
        ipId:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: ip_id
            generator:
                strategy: IDENTITY
    fields:
        netMacAddress:
            type: string
            nullable: false
            length: 17
            fixed: false
            comment: ''
            default: ''
            column: net_mac_address
        ipAddressV4:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
            default: ''
            column: ip_address_v4
        ipAddressV6:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
            default: ''
            column: ip_address_v6
        ipSubnet:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
            default: ''
            column: ip_subnet
        ipAddressVersion:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
            default: ''
            column: ip_address_version
        timestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
        firstTimestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
            column: first_timestamp
    manyToOne:
        system:
            targetEntity: System
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                system_id:
                    referencedColumnName: system_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
