Ehann\Bundle\OpenAwesomeBundle\Entity\SysHwMemory:
    type: entity
    table: sys_hw_memory
    indexes:
        system_id:
            columns:
                - system_id
    id:
        memoryId:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: memory_id
            generator:
                strategy: IDENTITY
    fields:
        memoryBank:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: memory_bank
        memoryType:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: memory_type
        memoryFormFactor:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: memory_form_factor
        memoryDetail:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: memory_detail
        memoryCapacity:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: memory_capacity
        memorySpeed:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: memory_speed
        memoryTag:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: memory_tag
        memorySerial:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: memory_serial
        timestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
        firstTimestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
            column: first_timestamp
    manyToOne:
        system:
            targetEntity: System
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                system_id:
                    referencedColumnName: system_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
