Ehann\Bundle\OpenAwesomeBundle\Entity\SysManInvoiceLine:
    type: entity
    table: sys_man_invoice_line
    id:
        lineId:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: line_id
            generator:
                strategy: IDENTITY
    fields:
        invoiceId:
            type: integer
            nullable: true
            unsigned: true
            comment: ''
            column: invoice_id
        lineText:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            default: ''
            column: line_text
        systemId:
            type: integer
            nullable: true
            unsigned: true
            comment: ''
            column: system_id
        manSerial:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            default: ''
            column: man_serial
        manAssetNumber:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            default: ''
            column: man_asset_number
        lineAmount:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            default: ''
            column: line_amount
        notes:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            default: ''
    lifecycleCallbacks: {  }
