Ehann\Bundle\OpenAwesomeBundle\Entity\SysManAudits:
    type: entity
    table: sys_man_audits
    indexes:
        system_id:
            columns:
                - system_id
    id:
        systemAuditsId:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: system_audits_id
            generator:
                strategy: IDENTITY
    fields:
        systemAuditsUsername:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            default: ''
            column: system_audits_username
        systemAuditsType:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            default: ''
            column: system_audits_type
        systemAuditsTime:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            default: ''
            column: system_audits_time
        systemAuditsIp:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
            default: ''
            column: system_audits_ip
        auditDebug:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: audit_debug
        auditWmiFails:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: audit_wmi_fails
        timestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
    manyToOne:
        system:
            targetEntity: System
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                system_id:
                    referencedColumnName: system_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
