Ehann\Bundle\OpenAwesomeBundle\Entity\SysManAdditionalFields:
    type: entity
    table: sys_man_additional_fields
    indexes:
        sys_man_additional_fields_group:
            columns:
                - group_id
    id:
        fieldId:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: field_id
            generator:
                strategy: IDENTITY
    fields:
        fieldName:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: field_name
        fieldType:
            type: string
            nullable: false
            length: null
            fixed: false
            comment: ''
            default: varchar
            column: field_type
        fieldValues:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: field_values
        fieldSysType:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: field_sys_type
        fieldDerivedType:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: field_derived_type
        fieldDerivedSql:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: field_derived_sql
        fieldPlacement:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: field_placement
    manyToOne:
        group:
            targetEntity: OaGroup
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                group_id:
                    referencedColumnName: group_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
