Ehann\Bundle\OpenAwesomeBundle\Entity\SysManNotes:
    type: entity
    table: sys_man_notes
    indexes:
        system_id:
            columns:
                - system_id
        user_id:
            columns:
                - user_id
    id:
        notesId:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: notes_id
            generator:
                strategy: IDENTITY
    fields:
        notesTitle:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            default: ''
            column: notes_title
        notesText:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: notes_text
        timestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
    manyToOne:
        system:
            targetEntity: System
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                system_id:
                    referencedColumnName: system_id
            orphanRemoval: false
        user:
            targetEntity: OaUser
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: user_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
