Ehann\Bundle\OpenAwesomeBundle\Entity\SysSwSharePerms:
    type: entity
    table: sys_sw_share_perms
    indexes:
        system_id:
            columns:
                - system_id
        sys_sw_share_perm_share_id:
            columns:
                - share_id
    id:
        permId:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: perm_id
            generator:
                strategy: IDENTITY
    fields:
        permPrefix:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: perm_prefix
        permName:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: perm_name
        permType:
            type: string
            nullable: false
            length: null
            fixed: false
            comment: ''
            default: local_user
            column: perm_type
        permAccess:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: perm_access
        timestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
        firstTimestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
            column: first_timestamp
    manyToOne:
        system:
            targetEntity: System
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                system_id:
                    referencedColumnName: system_id
            orphanRemoval: false
        share:
            targetEntity: SysSwShare
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                share_id:
                    referencedColumnName: share_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
