Ehann\Bundle\OpenAwesomeBundle\Entity\SysSwShare:
    type: entity
    table: sys_sw_share
    indexes:
        system_id:
            columns:
                - system_id
    id:
        shareId:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: share_id
            generator:
                strategy: IDENTITY
    fields:
        shareCaption:
            type: string
            nullable: false
            length: 250
            fixed: false
            comment: ''
            default: ''
            column: share_caption
        shareName:
            type: string
            nullable: false
            length: 250
            fixed: false
            comment: ''
            default: ''
            column: share_name
        sharePath:
            type: string
            nullable: false
            length: 250
            fixed: false
            comment: ''
            default: ''
            column: share_path
        shareSize:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
            default: ''
            column: share_size
        shareUsers:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            default: ''
            column: share_users
        timestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
        firstTimestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
            column: first_timestamp
    manyToOne:
        system:
            targetEntity: System
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                system_id:
                    referencedColumnName: system_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
