Ehann\Bundle\OpenAwesomeBundle\Entity\SysSwUser:
    type: entity
    table: sys_sw_user
    indexes:
        system_id:
            columns:
                - system_id
    id:
        userId:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: user_id
            generator:
                strategy: IDENTITY
    fields:
        userName:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: user_name
        userCaption:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
            column: user_caption
        userSid:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: user_sid
        userDomain:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: user_domain
        userDisabled:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            default: ''
            column: user_disabled
        userFullName:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: user_full_name
        userPasswordChangeable:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            default: ''
            column: user_password_changeable
        userPasswordExpires:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            default: ''
            column: user_password_expires
        userPasswordRequired:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            default: ''
            column: user_password_required
        userStatus:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: user_status
        userType:
            type: string
            nullable: false
            length: null
            fixed: false
            comment: ''
            default: local
            column: user_type
        timestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
        firstTimestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
            column: first_timestamp
    manyToOne:
        system:
            targetEntity: System
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                system_id:
                    referencedColumnName: system_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
