Ehann\Bundle\OpenAwesomeBundle\Entity\SysSwWebSiteHeader:
    type: entity
    table: sys_sw_web_site_header
    indexes:
        site_id:
            columns:
                - site_id
        system_id:
            columns:
                - system_id
    id:
        headerId:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: header_id
            generator:
                strategy: IDENTITY
    fields:
        headerAddress:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
            default: ''
            column: header_address
        headerPort:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: header_port
        headerHostname:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: header_hostname
        timestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
        firstTimestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
            column: first_timestamp
    manyToOne:
        system:
            targetEntity: System
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                system_id:
                    referencedColumnName: system_id
            orphanRemoval: false
        site:
            targetEntity: SysSwWebSite
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                site_id:
                    referencedColumnName: site_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
