Ehann\Bundle\OpenAwesomeBundle\Entity\SysSwVariable:
    type: entity
    table: sys_sw_variable
    indexes:
        system_id:
            columns:
                - system_id
    id:
        variableId:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: variable_id
            generator:
                strategy: IDENTITY
    fields:
        variableName:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: variable_name
        variableValue:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: variable_value
        timestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
        firstTimestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
            column: first_timestamp
    manyToOne:
        system:
            targetEntity: System
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                system_id:
                    referencedColumnName: system_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
