Ehann\Bundle\OpenAwesomeBundle\Entity\SysSwAntivirus:
    type: entity
    table: sys_sw_antivirus
    indexes:
        system_id:
            columns:
                - system_id
    id:
        virusId:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: virus_id
            generator:
                strategy: IDENTITY
    fields:
        virusManufacturer:
            type: string
            nullable: false
            length: 150
            fixed: false
            comment: ''
            default: ''
            column: virus_manufacturer
        virusVersion:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            default: ''
            column: virus_version
        virusName:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: virus_name
        virusUptodate:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            default: ''
            column: virus_uptodate
        virusDefDate:
            type: date
            nullable: false
            comment: ''
            default: '0000-00-00'
            column: virus_def_date
        timestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
        firstTimestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
            column: first_timestamp
    manyToOne:
        system:
            targetEntity: System
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                system_id:
                    referencedColumnName: system_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
