Ehann\Bundle\OpenAwesomeBundle\Entity\SysSwScheduledTask:
    type: entity
    table: sys_sw_scheduled_task
    indexes:
        system_id:
            columns:
                - system_id
    id:
        schedTaskId:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: sched_task_id
            generator:
                strategy: IDENTITY
    fields:
        schedTaskName:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: sched_task_name
        schedTaskNextRun:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            default: ''
            column: sched_task_next_run
        schedTaskStatus:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            default: ''
            column: sched_task_status
        schedTaskLastRun:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            default: ''
            column: sched_task_last_run
        schedTaskLastResult:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            default: ''
            column: sched_task_last_result
        schedTaskCreator:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            default: ''
            column: sched_task_creator
        schedTaskSchedule:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: sched_task_schedule
        schedTaskTask:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: sched_task_task
        schedTaskState:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
            default: ''
            column: sched_task_state
        schedTaskRunas:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            default: ''
            column: sched_task_runas
        timestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
        firstTimestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
            column: first_timestamp
    manyToOne:
        system:
            targetEntity: System
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                system_id:
                    referencedColumnName: system_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
