Ehann\Bundle\OpenAwesomeBundle\Entity\SysSwRoute:
    type: entity
    table: sys_sw_route
    indexes:
        system_id:
            columns:
                - system_id
    id:
        routeId:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: route_id
            generator:
                strategy: IDENTITY
    fields:
        destination:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            default: ''
        mask:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            default: ''
        metric:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
            default: ''
        nextHop:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            default: ''
            column: next_hop
        protocol:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
            default: ''
        type:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
            default: ''
        timestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
        firstTimestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
            column: first_timestamp
    manyToOne:
        system:
            targetEntity: System
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                system_id:
                    referencedColumnName: system_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
