Ehann\Bundle\OpenAwesomeBundle\Entity\SysSwLog:
    type: entity
    table: sys_sw_log
    indexes:
        system_id:
            columns:
                - system_id
    id:
        logId:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: log_id
            generator:
                strategy: IDENTITY
    fields:
        logName:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            default: ''
            column: log_name
        logFileName:
            type: string
            nullable: false
            length: 250
            fixed: false
            comment: ''
            default: ''
            column: log_file_name
        logFileSize:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: log_file_size
        logMaxFileSize:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: log_max_file_size
        logOverwrite:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
            default: ''
            column: log_overwrite
        timestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
        firstTimestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
            column: first_timestamp
    manyToOne:
        system:
            targetEntity: System
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                system_id:
                    referencedColumnName: system_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
