Ehann\Bundle\OpenAwesomeBundle\Entity\SysSwDatabaseDetails:
    type: entity
    table: sys_sw_database_details
    indexes:
        system_id:
            columns:
                - db_id
    id:
        detailsId:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: details_id
            generator:
                strategy: IDENTITY
    fields:
        systemId:
            type: integer
            nullable: true
            unsigned: true
            comment: ''
            column: system_id
        detailsName:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            default: ''
            column: details_name
        detailsInternalId:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            default: ''
            column: details_internal_id
        detailsInstance:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            default: ''
            column: details_instance
        detailsCurrentSize:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            default: ''
            column: details_current_size
        detailsCompatibilityMode:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            default: ''
            column: details_compatibility_mode
        detailsFilename:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            default: ''
            column: details_filename
        detailsCreationDate:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
            column: details_creation_date
        detailsLastAccessedDate:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            default: ''
            column: details_last_accessed_date
        detailsLastAccessedLoginName:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            default: ''
            column: details_last_accessed_login_name
        detailsLastAccessedHostname:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            default: ''
            column: details_last_accessed_hostname
        detailsLastAccessedProgram:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            default: ''
            column: details_last_accessed_program
        detailsLastAccessedDomain:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            default: ''
            column: details_last_accessed_domain
        detailsLastAccessedUsername:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            default: ''
            column: details_last_accessed_username
        detailsLastAccessedProtocol:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            default: ''
            column: details_last_accessed_protocol
        timestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
        firstTimestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
            column: first_timestamp
    manyToOne:
        db:
            targetEntity: SysSwDatabase
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                db_id:
                    referencedColumnName: db_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
