Ehann\Bundle\OpenAwesomeBundle\Entity\SysSwDatabase:
    type: entity
    table: sys_sw_database
    indexes:
        system_id:
            columns:
                - system_id
    id:
        dbId:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: db_id
            generator:
                strategy: IDENTITY
    fields:
        dbType:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            default: ''
            column: db_type
        dbVersion:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            default: ''
            column: db_version
        dbVersionString:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            default: ''
            column: db_version_string
        dbEdition:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            default: ''
            column: db_edition
        dbPort:
            type: integer
            nullable: true
            unsigned: true
            comment: ''
            column: db_port
        timestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
        firstTimestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
            column: first_timestamp
    manyToOne:
        system:
            targetEntity: System
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                system_id:
                    referencedColumnName: system_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
