Ehann\Bundle\OpenAwesomeBundle\Entity\SysSwPrintQueue:
    type: entity
    table: sys_sw_print_queue
    indexes:
        system_id:
            columns:
                - system_id
    id:
        queueId:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: queue_id
            generator:
                strategy: IDENTITY
    fields:
        queueSystemKey:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: queue_system_key
        queueName:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: queue_name
        queuePortName:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: queue_port_name
        queueIpAddress:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: queue_ip_address
        queueDescription:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: queue_description
        queueModel:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: queue_model
        queueManufacturer:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: queue_manufacturer
        queueShared:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: queue_shared
        queueSharedName:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: queue_shared_name
        queueLocation:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: queue_location
        queueColor:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: queue_color
        queueDuplex:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: queue_duplex
        queueType:
            type: string
            nullable: false
            length: null
            fixed: false
            comment: ''
            default: ''
            column: queue_type
        queueConnectionStatus:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: queue_connection_status
        timestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
        firstTimestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
            column: first_timestamp
    manyToOne:
        system:
            targetEntity: System
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                system_id:
                    referencedColumnName: system_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
