Ehann\Bundle\OpenAwesomeBundle\Entity\SysSwWebServer:
    type: entity
    table: sys_sw_web_server
    indexes:
        system_id:
            columns:
                - system_id
    id:
        webserverId:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: webserver_id
            generator:
                strategy: IDENTITY
    fields:
        webserverType:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: webserver_type
        webserverVersion:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: webserver_version
        webserverState:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: webserver_state
        webserverManDescription:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: webserver_man_description
        webserverLogEnabled:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: webserver_log_enabled
        webserverLogDir:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: webserver_log_dir
        webserverLogFormat:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: webserver_log_format
        webserverLogTimePeriod:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: webserver_log_time_period
        timestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
        firstTimestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
            column: first_timestamp
    manyToOne:
        system:
            targetEntity: System
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                system_id:
                    referencedColumnName: system_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
