Ehann\Bundle\OpenAwesomeBundle\Entity\SysSwWindows:
    type: entity
    table: sys_sw_windows
    indexes:
        system_id:
            columns:
                - system_id
    id:
        windowsId:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: windows_id
            generator:
                strategy: IDENTITY
    fields:
        windowsBuildNumber:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            default: ''
            column: windows_build_number
        windowsUserName:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: windows_user_name
        windowsClientSiteName:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: windows_client_site_name
        windowsDomainShort:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: windows_domain_short
        windowsDomainControllerAddress:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: windows_domain_controller_address
        windowsDomainControllerName:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: windows_domain_controller_name
        windowsDomainRole:
            type: string
            nullable: false
            length: 40
            fixed: false
            comment: ''
            default: ''
            column: windows_domain_role
        windowsPartOfDomain:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
            default: ''
            column: windows_part_of_domain
        windowsIdNumber:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: windows_id_number
        windowsTimeCaption:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: windows_time_caption
        windowsTimeDaylight:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: windows_time_daylight
        windowsBootDevice:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            default: ''
            column: windows_boot_device
        windowsCountryCode:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            default: ''
            column: windows_country_code
        windowsOrganisation:
            type: string
            nullable: false
            length: 80
            fixed: false
            comment: ''
            default: ''
            column: windows_organisation
        windowsLanguage:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            default: ''
            column: windows_language
        windowsRegisteredUser:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            default: ''
            column: windows_registered_user
        windowsServicePack:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            default: ''
            column: windows_service_pack
        windowsVersion:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            default: ''
            column: windows_version
        windowsInstallDirectory:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            default: ''
            column: windows_install_directory
        windowsActiveDirectoryOu:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            default: ''
            column: windows_active_directory_ou
        timestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
        firstTimestamp:
            type: datetime
            nullable: false
            comment: ''
            default: '0000-00-00 00:00:00'
            column: first_timestamp
    manyToOne:
        system:
            targetEntity: System
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                system_id:
                    referencedColumnName: system_id
            orphanRemoval: false
    lifecycleCallbacks: {  }
