ehann_open_awesome_audit_index:
    pattern:  /audit
    defaults: { _controller: EhannOpenAwesomeBundle:Audit:index }
    methods: [GET]

ehann_open_awesome_audit_post:
    pattern:  /audit
    defaults: { _controller: EhannOpenAwesomeBundle:Audit:post }
    methods: [POST]

ehann_open_awesome_audit_get:
    pattern:  /audit/{component}/{id}
    defaults: { _controller: EhannOpenAwesomeBundle:Audit:get }
