ehann_open_awesome_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: EhannOpenAwesomeBundle:Default:index }

ehann_open_awesome_audit_index:
    pattern:  /audit
    defaults: { _controller: EhannOpenAwesomeBundle:Audit:index }

ehann_open_awesome_audit_get:
    pattern:  /audit/{component}/{id}
    defaults: { _controller: EhannOpenAwesomeBundle:Audit:get }
