parameters:
    ehann_open_awesome.elasticsearch_client.class: Elasticsearch\Client

services:
    ehann_open_awesome.elasticsearch_client:
        class: %ehann_open_awesome.elasticsearch_client.class%

