parameters:
#    ehann_open_awesome.example.class: Ehann\Bundle\OpenAwesomeBundle\Example

services:
#    ehann_open_awesome.example:
#        class: %ehann_open_awesome.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
